name: Deploy dev

on:
  push:
    branches:
      - main

      # TODO: remove before merge
      # to test this branch, uncomment this
      # - logs
    paths:
      - "dev/*"
      - "dev/**/*"
      - ".github/workflows/deploy-dev.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bitops
      env:
        ENVIRONMENT: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
        AWS_DEFAULT_REGION: us-east-1
        TF_STATE_BUCKET: bitovi-angular-ngrx-chat-operations-dev
      run: |
        echo "running _scripts/deploy/deploy.sh"
        ./_scripts/deploy/deploy.sh